/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.13/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    implementation("org.jsoup:jsoup:1.18.1")

    implementation("org.knowm.xchart:xchart:3.8.8")

    implementation("org.json:json:20240303")
    implementation("com.google.code.gson:gson:2.10.1")

    // // Google API Client
    // implementation 'com.google.api-client:google-api-client:2.0.0'
    // // Custom Search Specific Library
    // implementation 'com.google.apis:google-api-services-customsearch:v1-rev20240821-2.0.0'
    // // JSON Parsing
    // implementation 'com.google.http-client:google-http-client-gson:1.43.3'

    // implementation 'com.squareup.okhttp3:okhttp:4.12.0'
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.withType<JavaExec> {
    standardInput = System.`in`
}